/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 82afd64bcfefdab246c1d77cd86166d0)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
	VITE_BASE_URL: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	CLOUDFLARE_DATABASE_ID: string;
	BETTER_AUTH_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	VITE_PAYMENT_PROVIDER: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	VITE_STRIPE_PRICE_PRO_MONTHLY: string;
	VITE_STRIPE_PRICE_PRO_YEARLY: string;
	VITE_STRIPE_PRICE_LIFETIME: string;
	CREEM_DEBUG: string;
	CREEM_API_KEY: string;
	CREEM_WEBHOOK_SECRET: string;
	VITE_CREEM_PRODUCT_PRO_MONTHLY: string;
	VITE_CREEM_PRODUCT_PRO_YEARLY: string;
	VITE_CREEM_PRODUCT_LIFETIME: string;
	RESEND_API_KEY: string;
	BEEHIIV_API_KEY: string;
	BEEHIIV_PUBLICATION_ID: string;
	DISCORD_WEBHOOK_URL: string;
	FEISHU_WEBHOOK_URL: string;
	VITE_CRISP_WEBSITE_ID: string;
	VITE_PLAUSIBLE_SCRIPT: string;
	VITE_GOOGLE_ANALYTICS_ID: string;
	VITE_UMAMI_SCRIPT: string;
	VITE_UMAMI_WEBSITE_ID: string;
	VITE_CLARITY_PROJECT_ID: string;
	FAL_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VITE_BASE_URL" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_DATABASE_ID" | "BETTER_AUTH_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "VITE_PAYMENT_PROVIDER" | "STRIPE_SECRET_KEY" | "STRIPE_WEBHOOK_SECRET" | "VITE_STRIPE_PRICE_PRO_MONTHLY" | "VITE_STRIPE_PRICE_PRO_YEARLY" | "VITE_STRIPE_PRICE_LIFETIME" | "CREEM_DEBUG" | "CREEM_API_KEY" | "CREEM_WEBHOOK_SECRET" | "VITE_CREEM_PRODUCT_PRO_MONTHLY" | "VITE_CREEM_PRODUCT_PRO_YEARLY" | "VITE_CREEM_PRODUCT_LIFETIME" | "RESEND_API_KEY" | "BEEHIIV_API_KEY" | "BEEHIIV_PUBLICATION_ID" | "DISCORD_WEBHOOK_URL" | "FEISHU_WEBHOOK_URL" | "VITE_CRISP_WEBSITE_ID" | "VITE_PLAUSIBLE_SCRIPT" | "VITE_GOOGLE_ANALYTICS_ID" | "VITE_UMAMI_SCRIPT" | "VITE_UMAMI_WEBSITE_ID" | "VITE_CLARITY_PROJECT_ID" | "FAL_KEY">> {}
}
